"""Auto-discover roaster storefronts from the shops already in the database.

Adding roasters by hand does not scale: ``data/raw/roaster_sites.txt`` (the
crawl frontier for the products scrape) and the seed list both have to be
curated URL-by-URL. But the ``shops`` stage already loads thousands of coffee
POIs from Overture, many with a ``website``, and the ``specialty`` stage already
flags the specialty ones. A specialty coffee shop whose website exposes a public
product catalog is, with high probability, a roaster we could be scraping.

This stage turns that latent signal into a review queue. It:

1. reads candidate shops from ``shop_shops`` (website present, and either
   ``is_specialty`` or ``roasts_in_house``),
2. drops any whose host is already known — already in ``roaster_sites.txt`` or
   already a ``roast_roasters.website`` — so it only surfaces *new* roasters,
3. probes each remaining host for a public catalog, reusing the products
   scraper's Shopify ``/products.json`` and WooCommerce Store API fetchers (and
   their coffee-vs-not product filter), and
4. writes the confirmed candidates to a **staging file** for human review
   (``data/processed/roaster_site_candidates.txt``), in the same format as
   ``roaster_sites.txt`` so approved URLs can be copied straight across.

It deliberately writes **no** database rows and does **not** touch
``roaster_sites.txt`` directly — a person vets the candidates first. Once vetted
URLs land in ``roaster_sites.txt``, the normal ``products`` →
``roaster_locations`` → ``graph`` flow ingests them.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from pathlib import Path

import duckdb
import httpx

from backend.ingest._common import managed_connection, site_host
from backend.ingest.shop_scrapers.product_scraper import (
    DEFAULT_SITES_FILE,
    USER_AGENT,
    _fetch_shopify,
    _fetch_woocommerce,
    extract_shopify,
    extract_woocommerce,
    read_sites,
)

DEFAULT_OUTPUT = Path("data/processed/roaster_site_candidates.txt")
# A single page is enough to confirm a catalog and get a representative count;
# we are detecting roasters here, not scraping their products.
PROBE_MAX_PRODUCTS = 50


@dataclass
class CandidateStub:
    """A shop website to probe (pre-network)."""

    site: str
    host: str
    shop_name: str
    city: str | None
    country: str | None


@dataclass
class Candidate:
    """A confirmed roaster storefront (post-probe), bound for the review file."""

    site: str
    shop_name: str
    city: str | None
    country: str | None
    platform: str  # "shopify" | "woocommerce"
    product_count: int


@dataclass
class DiscoveryCounts:
    candidates: int = 0  # shops probed (new hosts only)
    confirmed: int = 0  # probes that found a coffee catalog
    by_platform: dict[str, int] = field(default_factory=dict)
    output_path: str = ""


def _site_root(url: str | None) -> str | None:
    """Reduce any URL to ``https://<host>`` (no ``www.``, port, or path).

    Returns None for blanks and anything without a dotted host, so junk in
    ``website`` columns can't become a probe target.
    """
    host = site_host(url)
    return f"https://{host}" if host else None


def _host(root: str) -> str:
    return root.removeprefix("https://")


def known_hosts(
    roaster_websites: list[str], sites_file: str | Path = DEFAULT_SITES_FILE
) -> set[str]:
    """Hosts we already cover — the scrape frontier plus every roaster website."""
    hosts: set[str] = set()
    try:
        frontier = read_sites(sites_file)
    except FileNotFoundError:
        frontier = []
    for url in [*frontier, *roaster_websites]:
        root = _site_root(url)
        if root is not None:
            hosts.add(_host(root))
    return hosts


def select_candidates(rows: list[tuple], known: set[str]) -> list[CandidateStub]:
    """Turn ``shop_shops`` rows into de-duplicated probe targets.

    ``rows`` are ``(name, city, country, website)``. Skips blank/invalid sites,
    anything already known, and collapses multiple shops that share one host
    (chains, multiple locations of one roaster) to a single probe.
    """
    seen = set(known)
    out: list[CandidateStub] = []
    for name, city, country, website in rows:
        root = _site_root(website)
        if root is None:
            continue
        host = _host(root)
        if host in seen:
            continue
        seen.add(host)
        out.append(CandidateStub(site=root, host=host, shop_name=name, city=city, country=country))
    return out


def render_candidates_file(candidates: list[Candidate]) -> str:
    """Render confirmed candidates as a reviewable ``roaster_sites.txt``-style file."""
    header = [
        "# Auto-discovered roaster storefronts pending review.",
        "#",
        "# Generated by backend.ingest.roaster_discovery. Each entry is a coffee",
        "# shop from shop_shops whose website exposes a public product catalog",
        "# (Shopify /products.json or the WooCommerce Store API). Review these,",
        "# then move the approved URLs into data/raw/roaster_sites.txt to add them",
        "# to the products-scrape frontier. The format matches roaster_sites.txt",
        "# (one URL per line; blank lines and # comments are ignored), so approved",
        "# lines can be copied across as-is.",
        "",
    ]
    body: list[str] = []
    for c in sorted(candidates, key=lambda c: c.site):
        loc = ", ".join(p for p in (c.city, c.country) if p) or "location unknown"
        body.append(f"# {c.shop_name} — {loc} — {c.platform} ({c.product_count} products)")
        body.append(c.site)
        body.append("")
    text = "\n".join(header + body).rstrip()
    return text + "\n"


async def _probe_site(
    client: httpx.AsyncClient,
    stub: CandidateStub,
    sem: asyncio.Semaphore,
    probe_max: int,
) -> Candidate | None:
    """Confirm a catalog on one host. None if neither platform yields coffee."""
    async with sem:
        try:
            raw, _ = await _fetch_shopify(client, stub.site, probe_max)
            if raw:
                products = extract_shopify({"products": raw}, stub.site)
                if products:
                    return _confirm(stub, "shopify", len(products))
            woo_raw, _ = await _fetch_woocommerce(client, stub.site, probe_max)
            if woo_raw:
                products = extract_woocommerce(woo_raw, stub.site)
                if products:
                    return _confirm(stub, "woocommerce", len(products))
        except httpx.HTTPError, OSError:
            return None
    return None


def _confirm(stub: CandidateStub, platform: str, count: int) -> Candidate:
    return Candidate(
        site=stub.site,
        shop_name=stub.shop_name,
        city=stub.city,
        country=stub.country,
        platform=platform,
        product_count=count,
    )


async def _probe_all(
    stubs: list[CandidateStub], concurrency: int, probe_max: int
) -> list[Candidate]:
    sem = asyncio.Semaphore(concurrency)
    async with httpx.AsyncClient(headers={"User-Agent": USER_AGENT}) as client:
        tasks = [_probe_site(client, s, sem, probe_max) for s in stubs]
        results = await asyncio.gather(*tasks)
    return [c for c in results if c is not None]


def gather_stubs(
    db_path: str | None = None,
    conn: duckdb.DuckDBPyConnection | None = None,
    sites_file: str | Path = DEFAULT_SITES_FILE,
) -> list[CandidateStub]:
    """Read eligible shops and reduce them to new, de-duplicated probe targets.

    Pure DB read (no network), so the selection logic can be tested on its own.
    """
    with managed_connection(db_path, conn) as conn:
        rows = conn.execute(
            """
            SELECT name, city, country, website
            FROM shop_shops
            WHERE website IS NOT NULL AND trim(website) != ''
              AND (is_specialty OR roasts_in_house)
            """
        ).fetchall()
        roaster_websites = [
            r[0]
            for r in conn.execute(
                "SELECT website FROM roast_roasters WHERE website IS NOT NULL"
            ).fetchall()
        ]
    return select_candidates(rows, known_hosts(roaster_websites, sites_file))


def discover_roaster_sites(
    db_path: str | None = None,
    conn: duckdb.DuckDBPyConnection | None = None,
    output_path: str | Path = DEFAULT_OUTPUT,
    sites_file: str | Path = DEFAULT_SITES_FILE,
    concurrency: int = 8,
    probe_max: int = PROBE_MAX_PRODUCTS,
    write: bool = True,
) -> DiscoveryCounts:
    """Probe specialty-shop websites for catalogs; stage the hits for review."""
    stubs = gather_stubs(db_path, conn, sites_file)

    confirmed = asyncio.run(_probe_all(stubs, concurrency, probe_max)) if stubs else []

    by_platform: dict[str, int] = {}
    for c in confirmed:
        by_platform[c.platform] = by_platform.get(c.platform, 0) + 1

    out = Path(output_path)
    if write:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(render_candidates_file(confirmed), encoding="utf-8")

    return DiscoveryCounts(
        candidates=len(stubs),
        confirmed=len(confirmed),
        by_platform=by_platform,
        output_path=str(out),
    )


if __name__ == "__main__":
    result = discover_roaster_sites()
    print(
        f"Probed {result.candidates} new shop sites, "
        f"confirmed {result.confirmed} roaster catalogs {result.by_platform}"
    )
    if result.confirmed:
        print(f"  Review staged candidates → {result.output_path}")
